'use client';

import React, { useState } from 'react';
import { toPng } from 'html-to-image';
import { jsPDF } from 'jspdf';
import { Download, FileImage, FileText } from 'lucide-react';
import { useLineup } from '@/context/LineupContext';

/**
 * Lineup exporter component
 * Exports lineup as PNG or PDF
 */
export function LineupExporter() {
  const { lineupState } = useLineup();
  const [isExporting, setIsExporting] = useState(false);

  /**
   * Export lineup as PNG image
   */
  const exportToPNG = async () => {
    setIsExporting(true);
    try {
      const element = document.getElementById('lineup-field');
      if (!element) {
        console.error('Lineup field element not found');
        return;
      }

      const dataUrl = await toPng(element, {
        quality: 1.0,
        width: 2400,
        height: 3200,
        backgroundColor: '#1a1a1a',
        pixelRatio: 3,
      });

      // Download
      const link = document.createElement('a');
      link.download = `austin-fc-lineup-${lineupState.formation.shortName}-${new Date().toISOString().split('T')[0]}.png`;
      link.href = dataUrl;
      link.click();
    } catch (error) {
      console.error('Error exporting PNG:', error);
      alert('Failed to export PNG. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  /**
   * Export lineup as PDF
   */
  const exportToPDF = async () => {
    setIsExporting(true);
    try {
      const element = document.getElementById('lineup-field');
      if (!element) {
        console.error('Lineup field element not found');
        return;
      }

      const dataUrl = await toPng(element, {
        quality: 1.0,
        width: 2400,
        height: 3200,
        backgroundColor: '#1a1a1a',
        pixelRatio: 3,
      });

      // Create PDF (A4 portrait)
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      // Add metadata
      const formationName = lineupState.formation.name;
      const date = new Date().toLocaleDateString();

      // Add title
      pdf.setFontSize(20);
      pdf.setTextColor(164, 216, 37); // Verde color
      pdf.text('Austin FC Lineup', 105, 20, { align: 'center' });

      // Add formation info
      pdf.setFontSize(12);
      pdf.setTextColor(255, 255, 255);
      pdf.text(`Formation: ${formationName}`, 105, 30, { align: 'center' });
      pdf.text(`Date: ${date}`, 105, 37, { align: 'center' });

      // Add lineup image
      const imgWidth = 180;
      const imgHeight = 240;
      const xOffset = (210 - imgWidth) / 2; // Center on A4 width (210mm)
      pdf.addImage(dataUrl, 'PNG', xOffset, 45, imgWidth, imgHeight);

      // Add watermark
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text('Generated by Verde Manager | austinfc-gm.vercel.app', 105, 290, { align: 'center' });

      // Save
      pdf.save(`austin-fc-lineup-${lineupState.formation.shortName}-${new Date().toISOString().split('T')[0]}.pdf`);
    } catch (error) {
      console.error('Error exporting PDF:', error);
      alert('Failed to export PDF. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="flex items-center gap-2">
      {isExporting && (
        <div className="flex items-center gap-2 text-[var(--verde)] text-sm">
          <Download className="w-4 h-4 animate-bounce" />
          <span>Exporting...</span>
        </div>
      )}

      <button
        onClick={exportToPNG}
        disabled={isExporting || lineupState.startingXI.length < 11}
        className="flex items-center gap-2 px-4 py-2 bg-[var(--verde)] text-black font-semibold rounded-lg hover:bg-[var(--verde)]/90 transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
        title={lineupState.startingXI.length < 11 ? 'Complete your starting XI first' : 'Export as PNG image'}
      >
        <FileImage className="w-4 h-4" />
        Export PNG
      </button>

      <button
        onClick={exportToPDF}
        disabled={isExporting || lineupState.startingXI.length < 11}
        className="flex items-center gap-2 px-4 py-2 bg-white/10 text-white font-semibold rounded-lg hover:bg-white/20 transition-colors text-sm disabled:opacity-50 disabled:cursor-not-allowed"
        title={lineupState.startingXI.length < 11 ? 'Complete your starting XI first' : 'Export as PDF document'}
      >
        <FileText className="w-4 h-4" />
        Export PDF
      </button>
    </div>
  );
}
